### ISSUE TITLE
nawk: No such file or directory

### ISSUE THREAD

**Issue by Kamilcuk** [ta2gch/pkgbrew#1]
Hey! I want to say : amazing code! Great job!

So after installation I got:

```
$ bmake
HOME/.pkgbrew/src/mk/pkgformat/pkg/list-dependencies: line 46: HOME/.pkgbrew/bin/nawk: No such file or directory
===> Skipping vulnerability checks.
WARNING: No HOME/.pkgbrew/var/db/pkg/pkg-vulnerabilities file found.
WARNING: To fix run: `HOME/.pkgbrew/sbin/pkg_admin -K HOME/.pkgbrew/var/db/pkg fetch-pkg-vulnerabilities'.
===> Installing dependencies for nawk-20121220nb1
HOME/.pkgbrew/src/mk/pkgformat/pkg/list-dependencies: line 46: HOME/.pkgbrew/bin/nawk: No such file or directory
*** Error code 1

Stop.
bmake: stopped in HOME/.pkgbrew/src/lang/nawk
```

and _exactly_ the same error when running `pkgbrew install`.

I was able to track missing nawk, it comes from [this from mk.conf.tpl](https://github.com/tani/pkgbrew/blob/master/src/mk.conf.tpl#L17). What it's doing there? Removing it or replacing with `/usr/bin/awk` solves the issue of missing nawk.

**Comment by tani** [comment]
Thank you for using my software and giving your nice feedback.
I switched pkgsrc official source today. I hope this change makes your issue solved.

Please reinstall pkgbrew.

```sh
$ rm -rf ~/.pkgbrew
$ # Do the installation agin
```

**Comment by tani** [comment]
@Kamilcuk How are you? Please close the issue if it works well. Thanks!
